const express = require('express');
const router = express.Router();
const dataController = require('../controllers/dataController');
const { verifyToken, verifyUserActive } = require('../middlewares/authMiddleware');

router.delete('/sheet-data', verifyToken, verifyUserActive, dataController.deleteSheetData);
router.get('/headers-with-validated-data', verifyToken, verifyUserActive, dataController.getHeadersWithValidatedData);
router.get('/headers-with-search-data', verifyToken, verifyUserActive, dataController.getFilteredHeaderData);
router.get('/headers-with-duplicate-data', verifyToken, verifyUserActive, dataController.getHeadersWithDuplicateData);
router.get('/pag-sheet-data', verifyToken, verifyUserActive, dataController.getValidatedPageData);
router.get('/export-data', verifyToken, verifyUserActive, dataController.getTemplateDataWithExcel);
router.put('/update-rows', verifyToken, verifyUserActive, dataController.updateRows);
router.put('/bulk-update', verifyToken, verifyUserActive, dataController.bulkUpdateData);
router.put('/padding', verifyToken, verifyUserActive, dataController.addPadding);
router.put('/apply-calculation', verifyToken, verifyUserActive, dataController.applyCalculations);
router.post('/add-row/:templateId/:sheetId', verifyToken, verifyUserActive, dataController.addRow);
router.put('/find-zipcode', verifyToken, verifyUserActive, dataController.findZipCodes);
router.put('/score-conversion', verifyToken, verifyUserActive, dataController.scoreConversion);
router.put('/cip-conversion', verifyToken, verifyUserActive, dataController.cipConversion);
router.put('/facility-zip-fill', verifyToken, verifyUserActive, dataController.FacilityZipFiller);
router.put('/zip-county-conversion', verifyToken, verifyUserActive, dataController.zipCountyConversion);
router.post('/apply-quality-rules', verifyToken, verifyUserActive, dataController.evaluateRulesAndReturnFilteredData);
router.delete('/delete-row/:templateId/:sheetId/:rowIndex', verifyToken, verifyUserActive, dataController.deleteRow);
router.put('/award-calculation', verifyToken, verifyUserActive, dataController.calculateAwardInfo);
router.put('/find-pell', verifyToken, verifyUserActive, dataController.calculatePellFlag);
router.put('/replace-value', verifyToken, verifyUserActive, dataController.bulkReplaceValues);
router.post('/evaluate-conditions', verifyToken, verifyUserActive, dataController.evaluateSheetDataWithConditions);
router.put('/delete-rows-by-condition', verifyToken, verifyUserActive, dataController.deleteSheetDataByConditions);
router.post('/apply-conditional-rule', verifyToken, verifyUserActive, dataController.evaluateSheetDataAndAssign);
router.post('/preview-evaluate-conditions',verifyToken, verifyUserActive, dataController.evaluateSheetDataPreview);
router.put('/evaluate-and-delete', verifyToken, verifyUserActive, dataController.evaluateSheetDataAndDelete);
router.post('/status-values', verifyToken, verifyUserActive, dataController.getStatusValues);
router.post('/header-values', verifyToken, verifyUserActive, dataController.getHeaderValues);
router.put('/auto-fill-award', verifyToken, verifyUserActive, dataController.autoFillInternationalAwards);
router.post('/acceptance-status-values', verifyToken, verifyUserActive, dataController.getAcceptanceStatusValues);
router.post('/all-status-values', verifyToken, verifyUserActive, dataController.getAllStatusValues);
router.post('/export-data-conditions', verifyToken, verifyUserActive, dataController.exportDataWithConditions);
router.put('/bulk-update-yn', verifyToken, verifyUserActive, dataController.bulkUpdateYesNo);
router.put('/evaluate-bands', verifyToken, verifyUserActive, dataController.evaluateBandsAndAssign);
router.put('/assign-element', verifyToken, verifyUserActive, dataController.evaluateMatrixAndAssignElement);
router.put('/update-institutional-code', verifyToken, verifyUserActive, dataController.updateInstitutionalCode);
router.put('/clear-column-data', verifyToken, verifyUserActive, dataController.clearHeaderData);
router.put('/clear-empty-columns', verifyToken, verifyUserActive, dataController.clearEmptyHeaderColumns);
router.put('/normalize-null-values', verifyToken, verifyUserActive, dataController.normalizeNullValues);

module.exports = router;