const express = require('express');
const router = express.Router();
const ruleController = require('../controllers/RuleController');
const { verifyToken, verifyUserActive } = require('../middlewares/authMiddleware');

router.delete('/rules/:id', verifyToken, verifyUserActive, ruleController.deleteRule);
router.post('/rules', verifyToken, verifyUserActive, ruleController.createRule);
router.put('/rules/:id', verifyToken, verifyUserActive, ruleController.updateRule);
router.get('/rules/:templateId', verifyToken, verifyUserActive, ruleController.getAllRules);
router.get('/rules', verifyToken, verifyUserActive, ruleController.getRuleById);
router.get('/bulk-rules', verifyToken, verifyUserActive, ruleController.getBulkRulesByTemplateId);
router.post('/bulk-rule', verifyToken, verifyUserActive, ruleController.createBulkRule);
router.put('/bulk-rule/:id', verifyToken, verifyUserActive, ruleController.updateBulkRule);
router.put('/apply-bulk-rule', verifyToken, verifyUserActive, ruleController.applyBulkRule);
router.delete('/bulk-rule', verifyToken, verifyUserActive, ruleController.deleteBulkRule);
router.post('/conditional-rule', verifyToken, verifyUserActive, ruleController.createConditionalRule);
router.put('/conditional-rule', verifyToken, verifyUserActive, ruleController.updateConditionalRule);
router.get('/conditional-rules/:templateId', verifyToken, verifyUserActive, ruleController.getAllConditionalRules);
router.get('/conditional-rule', verifyToken, verifyUserActive, ruleController.getConditionalRuleById);
router.delete('/conditional-rule', verifyToken, verifyUserActive, ruleController.deleteConditionalRule);
router.post('/population-rule', verifyToken, verifyUserActive, ruleController.createPopulationRule);
router.get('/population-rules/:templateId/:ruleType', verifyToken, verifyUserActive, ruleController.getPopulationRuleByTemplateId);
router.get('/population-rule', verifyToken, verifyUserActive, ruleController.getPopulationRuleById);
router.delete('/population-rule', verifyToken, verifyUserActive, ruleController.deletePopulationRule);
router.put('/population-rule', verifyToken, verifyUserActive, ruleController.updatePopulationRule);
router.post('/auto-population-rule', verifyToken, verifyUserActive, ruleController.autoPopulationRule);
router.post('/band-rule', verifyToken, verifyUserActive, ruleController.createBandRule);
router.put('/band-rule/:id', verifyToken, verifyUserActive, ruleController.updateBandRule);
router.get('/band-rules', verifyToken, verifyUserActive, ruleController.getBandRulesByTemplateId);
router.delete('/band-rule', verifyToken, verifyUserActive, ruleController.deleteBandRule);
router.post('/element-matrix', verifyToken, verifyUserActive, ruleController.createElementMatrix);
router.put('/element-matrix/:id', verifyToken, verifyUserActive, ruleController.updateElementMatrix);
router.delete('/element-matrix', verifyToken, verifyUserActive, ruleController.deleteElementMatrix);
router.get('/element-matrices', verifyToken, verifyUserActive, ruleController.getElementMatricesByTemplateId);

module.exports = router;