const desiredOrder = [
  "Institution_Code",
  "Student_ID",
  "Alternate_Student_ID",
  "Last_Name",
  "First_Name",
  "Middle_Name/Initial",
  "Student_Address_1",
  "Student_Address_2",
  "Student_City",
  "Student_State",
  "Student_ZIP",
  "Student_ZIP_9",
  "Sectional_Center_Facility_ZIP",
  "Home_County",
  "Y/N Student_In_County",
  "Cell_Phone_#",
  "Student_Primary_Email",
  "Student_Email_2",
  "Date_Of_Birth",
  "Gender",
  "Academic_Year",
  "Academic_Term",
  "First_Year/Transfer/Continuing/Readmit/Online",
  "Admissions_Funnel_Stage",
  "Application_Type",
  "Admit_Type_R_EA_ED_Etc.",
  "Academic_Standing_U/G/P",
  "Y/N Bought_Through_Search",
  "Date_Of_Search_Purchase",
  "Y/N Student_Inquired",
  "Date_Of_Inquiry",
  "Inquiry_Source",
  "Inquiry_Model_Score",
  "Y/N Stealth_App",
  "%_of_Stealth_App",
  "Y/N Student_Applied",
  "Date_Of_Application",
  "Y/N Student_Admitted",
  "Date_Of_Admission",
  "Y/N Student_Readmitted",
  "Date_Of_Readmission",
  "Y/N Student_Confirmed",
  "Date_Of_Confirmation",
  "Y/N Student_Cancelled",
  "Date_Of_Cancellation",
  "Y/N Student_Enrolled",
  "Date_Term_Starts",
  "Admission_Counselor",
  "Recruitment_Territory",
  "Major_At_Admission",
  "Department_At_Admission",
  "Major2_At_Admission",
  "Department2_At_Admission",
  "College/Division_At_Admission",
  "Campus/Site",
  "Home_Country",
  "Citizenship_Status",
  "Y/N International_Student",
  "Y/N Veteran",
  "Religious_Code",
  "Y/N Student_Religion=School_Denomination",
  "Y/N First_Generation_Student",
  "Y/N Emerging_Population",
  "Y/N Legacy_Student",
  "Y/N Early_Admit_Student",
  "Y/N Early_Enrollment_Decision",
  "Y/N Early_Aid",
  "Y/N Funded_Athlete",
  "Y/N Roster_Athlete",
  "Y/N Coach_Recruited_Athlete",
  "First_Sport",
  "Second_Sport",
  "Third_Sport",
  "Fourth_Sport",
  "Fifth_Sport",
  "Extracurricular_1",
  "Y/N Recruited for Extracurricular1",
  "Extracurricular_2",
  "Y/N Recruited for Extracurricular2",
  "Distance_From_Campus",
  "College_Board_EPS_Code",
  "Encoura_Scoring",
  "MacIG_Persona",
  "Travel_Interactions_With_Student",
  "Student_Inititiated_Interest",
  "Campus_Initiated_Outreach",
  "Alumni_Initiated_Outreach",
  "Phone_Outreach",
  "Total_Outreach_Contacts",
  "Attendance_At_Scholarship_Day",
  "Attendance_At_Open_House",
  "Campus_Visit(s)",
  "Attended_Orientation",
  "MacIG_Visit_Index",
  "Y/N Is_Student_Test_Optional",
  "ACT_Converted_From_SAT",
  "ACT_Composite",
  "Y/N ACT_Official",
  "SAT_Converted_From_ACT",
  "SAT_Composite",
  "Y/N SAT_Official",
  "TOEFL_Score",
  "Institution_Provided_Test_Score_1",
  "Institution_Provided_Test_Score_2",
  "Math_Placement_Test_Score",
  "English_Placement_Test_Score",
  "Reading_Placement_Test_Score",
  "Other_Placement_Test_Score",
  "Classic_Learning_Test(CLT)_Score",
  "Special_Diploma",
  "Y/N Student_Applied_To_Honors_Program",
  "High_School_Code",
  "High School Name",
  "Is_HS_Data_Self-reported/Transcript",
  "Rank_In_Class",
  "Number_In_Class",
  "Class_Percentage",
  "HSGPA_Weighted",
  "Weighted_GPA_Scale(5,6,7,etc)",
  "HSGPA_Unweighted",
  "Unweighted_GPA_Scale",
  "Weighted_GPA_On_4.00_Scale",
  "Unweighted_On_4.00_Scale",
  "Last_College_Attended_Code",
  "Last_College_Attended_Name",
  "Y/N Is_College_Data_Self-reported/Transcript",
  "Total_College_Credits",
  "Cumulative_CGPA",
  "CGPA_Of_Transferred_Credits",
  "Type_Of_Degree_At_Prior_Institution",
  "Registration_Hours_With_Us",
  "Date_Registered_With_Us",
  "Housing_Code",
  "Housing_Status_From_Application",
  "Housing_Status_From_Housing",
  "Ethnic_Code",
  "Y/N Hispanic",
  "First_Race_Code",
  "Second_Race_Code",
  "Third_Race_Code",
  "Fourth_Race_Code",
  "Fifth_Race_Code",
  "Y/N Did_Student_Submit_Our_FA_Application",
  "Date_Student_Completed_FA_Form",
  "Y/N Will_Student_File_FAFSA",
  "Y/N FAFSA_Received",
  "Date_FAFSA_Received",
  "Y/N Selected_For_Verification",
  "Date_Verification_Completed",
  "ISIR_Status",
  "Y/N Is_ISIR_Valid",
  "Y/N Is_SAI_Estimated",
  "SAI",
  "Dependency_Status",
  "Student_Marital_Status",
  "Total_Income_From_ISIR",
  "FAFSA_State_Of_Residence",
  "HS_Diploma/GED/Home_Schooled_Other",
  "Degree_Plan_From_ISIR",
  "Y/N Is_Student_Seeking_Bachelor's_Degree",
  "Year_In_College/Academic_Level",
  "Y/N Is_Student_Applying_As_Grad_Student",
  "Parent_Educational_Level",
  "Household_Size",
  "Number_In_College",
  "Academic_Load_F/H/Etc.",
  "Y/N Is_Student_Packaged",
  "Date_Of_First_Package",
  "Date_Of_Revised_Package",
  "Y/N Student_Accepted_Award",
  "Date_Of_Award_Acceptance",
  "Student_Reaction_To_Award",
  "Date_Student_Filed_Institutional_Aid_Form",
  "Institutional_SAI_Using_Our_Form",
  "Institutional_Total_Income",
  "Institutional_Parent_Income",
  "Institutional_Student_Income",
  "Y/N Is_Student_Pell_Eligible",
  "Y/N Student/Parent_Denied_PLUS",
  "Y/N Is_Student_Receiving_Talent_Aid",
  "Y/N Student_Eligible_For_In-state_Tuition",
  "Type_Of_Tuition_Eligibility",
  "Y/N Zero_SAI_For_Student",
  "Y/N Student_Is_Employee_Benefit",
  "Y/N Student_Is_Tuition_Exchange",
  "Y/N Student_Is_State_Grant_Eligible",
  "Y/N Professional_Judgement_Performed",
  "Academic_Rating",
  "Calculated_Index",
  "Awarding_Population",
  "Awarding_Sub-population",
  "Financial_Band",
  "Academic_Band",
  "Element_Number",
  "Merit Only Students",
  "Mac_Behavior_Cluster",
  "SAT_Bin",
  "ACT_Bin",
  "Distance_Bin",
  "Cost_Sensitive_Score",
  "Change_Effect_Of_$1000_Aid",
  "Personicx_Cluster_Identifier",
  "Personicx_Group_Identifier",
  "Student_Price_Elasticity",
  "Packaging_Variance",
  "Optimal_Institutional_Aid_Award",
  "Probability_Of_Enrolling",
  "Model_Score",
  "Model_Score_Bin",
  "Estimated_Income",
  "Income_Level",
  "Student_Financial_Need",
  "Total_Need_Met",
  "%_Of_Need_Met",
  "GAP/Unmet_Need",
  "%_Of_Need_Met_W/Gift_Aid",
  "Institutional_Merit_As_%_Of_Need_Met",
  "Total_Institutional_Merit_Gift",
  "Total_Institutional_Need_Gift",
  "Total_Institutional_Other_Gift",
  "Total_Institutional_Honors_Gift",
  "Total_Institutional_Unfunded_Gift",
  "Total_Institutional_Gift",
  "Total_Institutional_Work",
  "Total_Need_Based_Aid",
  "Total_Merit+Need_Gift",
  "Total_Outside_Gift+Work+Loan",
  "Total_Tuition_Exchange",
  "Total_Employee_Benefit",
  "Total_Performance_Gift",
  "Total_Elite_Gift",
  "Total_Ouside_Gift_Aid",
  "Total_Outside_Loan_Aid",
  "Total_Outside_Work_Aid",
  "Total_Private_Aid_G+W+L",
  "Total_Private_Gift_Aid",
  "Total_Private_Loan_Aid",
  "Total_Private_Work_Aid",
  "Total_Federal_Aid_G+W+L",
  "Total_Federal_Gift_Aid",
  "Total_Federal_Loan_Aid",
  "Total_Federal_Work_Aid",
  "Total_State_Aid_G+W+L",
  "Total_State_Gift_Aid",
  "Total_Gift_Aid",
  "Target_Gift_Aid",
  "Total_Work_Aid",
  "Total_Loan_Aid",
  "NACUBO_Discount_Rate",
  "Total_Discount_Rate",
  "Campus_Discount Rate",
  "Tuition_Discount_Rate",
  "Net_Charges_To_Student",
  "Net_Tuition_Revenue",
  "Net_Tuition/Fee_Revenue",
  "Total_Direct_Costs",
  "2_Semester_COA",
  "2_Semester_Tuition",
  "2_Semester_Room",
  "2_Semester_Meals",
  "2_Semester_Fees",
  "2_Semester_Books_Supplies",
  "2_Semester_Transportation",
  "2_Semester_Other_Indirect_Charges",
  "Awd_Cd1",
  "Awd_Amt1",
  "Awd_Status1",
  "Awd_CR1",
  "Awd_Cd2",
  "Awd_Amt2",
  "Awd_Status2",
  "Awd_CR2",
  "Awd_Cd3",
  "Awd_Amt3",
  "Awd_Status3",
  "Awd_CR3",
  "Awd_Cd4",
  "Awd_Amt4",
  "Awd_Status4",
  "Awd_CR4",
  "Awd_Cd5",
  "Awd_Amt5",
  "Awd_Status5",
  "Awd_CR5",
  "Awd_Cd6",
  "Awd_Amt6",
  "Awd_Status6",
  "Awd_CR6",
  "Awd_Cd7",
  "Awd_Amt7",
  "Awd_Status7",
  "Awd_CR7",
  "Awd_Cd8",
  "Awd_Amt8",
  "Awd_Status8",
  "Awd_CR8",
  "Awd_Cd9",
  "Awd_Amt9",
  "Awd_Status9",
  "Awd_CR9",
  "Awd_Cd10",
  "Awd_Amt10",
  "Awd_Status10",
  "Awd_CR10",
  "Awd_Cd11",
  "Awd_Amt11",
  "Awd_Status11",
  "Awd_CR11",
  "Awd_Cd12",
  "Awd_Amt12",
  "Awd_Status12",
  "Awd_CR12",
  "Awd_Cd13",
  "Awd_Amt13",
  "Awd_Status13",
  "Awd_CR13",
  "Awd_Cd14",
  "Awd_Amt14",
  "Awd_Status14",
  "Awd_CR14",
  "Awd_Cd15",
  "Awd_Amt15",
  "Awd_Status15",
  "Awd_CR15",
  "Awd_Cd16",
  "Awd_Amt16",
  "Awd_Status16",
  "Awd_CR16",
  "Awd_Cd17",
  "Awd_Amt17",
  "Awd_Status17",
  "Awd_CR17",
  "Awd_Cd18",
  "Awd_Amt18",
  "Awd_Status18",
  "Awd_CR18",
  "Awd_Cd19",
  "Awd_Amt19",
  "Awd_Status19",
  "Awd_CR19",
  "Awd_Cd20",
  "Awd_Amt20",
  "Awd_Status20",
  "Awd_CR20",
  "Parent_Phone_1",
  "Parent_Phone_2",
  "Parent_Email_1",
  "Parent_Email_2",
  "Original_Start_Term",
  "Academic_Advisor_Name",
  "Residence_Hall_Assignment",
  "College_Where_Student_Enrolled",
  "Clearinghouse_Code_Of_College_Attended",
  "Y/N Student_Persisted_To_Second_Term",
  "First_Term_College_GPA",
  "Y/N Student_Persisted_To_Second_Fall",
  "First_Year_College_GPA",
  "Major_At_Enrollment",
  "Department_At_Enrollment",
  "Major2_At_Enrollment",
  "Department2_At_Enrollment",
  "Total_Hours_Attempted",
  "Total_Hours_Completed",
  "User_Field_1",
  "User_Field_2",
  "User_Field_3",
  "User_Field_4",
  "User_Field_5",
  "User_Field_6",
  "User_Field_7",
  "User_Field_8",
  "User_Field_9",
  "User_Field_10",
  "User_Field_11",
  "User_Field_12",
  "User_Field_13",
  "User_Field_14",
  "User_Field_15",
  "User_Field_16",
  "User_Field_17",
  "User_Field_18",
  "User_Field_19",
  "User_Field_20",
  "User_Field_21",
  "User_Field_22",
  "User_Field_23",
  "User_Field_24",
  "User_Field_25",
  "User_Field_26",
  "User_Field_27",
  "User_Field_28",
  "User_Field_29",
  "User_Field_30",
  "User_Field_31",
  "User_Field_32",
  "User_Field_33",
  "User_Field_34",
  "User_Field_35",
  "User_Field_36",
  "User_Field_37",
  "User_Field_38",
  "User_Field_39",
  "User_Field_40",
  "User_Field_41",
  "User_Field_42",
  "User_Field_43",
  "User_Field_44",
  "User_Field_45",
  "User_Field_46",
  "User_Field_47",
  "User_Field_48",
  "User_Field_49",
  "User_Field_50",
  "User_Field_51",
  "User_Field_52",
  "User_Field_53",
  "User_Field_54",
  "User_Field_55",
  "User_Field_56",
  "User_Field_57",
  "User_Field_58",
  "User_Field_59",
  "User_Field_60",
  "User_Field_61",
  "User_Field_62",
  "User_Field_63",
  "User_Field_64",
  "User_Field_65",
  "User_Field_66",
  "User_Field_67",
  "User_Field_68",
  "User_Field_69",
  "User_Field_70",
  "User_Field_71",
  "User_Field_72",
  "User_Field_73",
  "User_Field_74",
  "User_Field_75",
  "User_Field_76",
  "User_Field_77",
  "User_Field_78",
  "User_Field_79",
  "User_Field_80",
  "User_Field_81",
  "User_Field_82",
  "User_Field_83",
  "User_Field_84",
  "User_Field_85",
  "User_Field_86",
  "User_Field_87",
  "User_Field_88",
  "User_Field_89",
  "User_Field_90",
  "User_Field_91",
  "User_Field_92",
  "User_Field_93",
  "User_Field_94",
  "User_Field_95",
  "User_Field_96",
  "User_Field_97",
  "User_Field_98",
  "User_Field_99",
  "User_Field_100"
];


const desiredOrderType = [
  "text",
  "text",
  "text",
  "text",
  "text",
  "text",
  "text",
  "text",
  "text",
  "text",
  "text",
  "text",
  "text",
  "text",
  "Y/N",
  "text",
  "text",
  "text",
  "Date",
  "text",
  "text",
  "text",
  "text",
  "text",
  "text",
  "text",
  "text",
  "Y/N",
  "Date",
  "Y/N",
  "Date",
  "text",
  "text",
  "Y/N",
  "decimal",
  "Y/N",
  "Date",
  "Y/N",
  "Date",
  "Y/N",
  "Date",
  "Y/N",
  "Date",
  "Y/N",
  "Date",
  "Y/N",
  "Date",
  "text",
  "text",
  "text",
  "text",
  "text",
  "text",
  "text",
  "text",
  "text",
  "text",
  "Y/N",
  "Y/N",
  "text",
  "Y/N",
  "Y/N",
  "Y/N",
  "Y/N",
  "Y/N",
  "Y/N",
  "Y/N",
  "Y/N",
  "Y/N",
  "Y/N",
  "Y/N",
  "text",
  "text",
  "text",
  "text",
  "text",
  "text",
  "Y/N",
  "text",
  "Y/N",
  "text",
  "text",
  "text",
  "text",
  "text",
  "text",
  "text",
  "text",
  "text",
  "text",
  "text",
  "text",
  "text",
  "text",
  "Y/N",
  "text",
  "text",
  "Y/N",
  "text",
  "text",
  "Y/N",
  "text",
  "text",
  "text",
  "text",
  "text",
  "text",
  "text",
  "text",
  "text",
  "Y/N",
  "text",
  "text",
  "text",
  "text",
  "text",
  "text",
  "text",
  "text",
  "text",
  "text",
  "text",
  "text",
  "text",
  "text",
  "Y/N",
  "text",
  "text",
  "text",
  "text",
  "text",
  "Date",
  "text",
  "text",
  "text",
  "text",
  "Y/N",
  "text",
  "text",
  "text",
  "text",
  "text",
  "Y/N",
  "Date",
  "Y/N",
  "Y/N",
  "Date",
  "Y/N",
  "Date",
  "text",
  "Y/N",
  "Y/N",
  "text",
  "text",
  "text",
  "integer",
  "text",
  "text",
  "text",
  "Y/N",
  "text",
  "Y/N",
  "text",
  "text",
  "text",
  "text",
  "Y/N",
  "Date",
  "Date",
  "Y/N",
  "Date",
  "text",
  "Date",
  "text",
  "text",
  "integer",
  "text",
  "Y/N",
  "Y/N",
  "Y/N",
  "Y/N",
  "text",
  "Y/N",
  "Y/N",
  "Y/N",
  "Y/N",
  "Y/N",
  "text",
  "text",
  "text",
  "text",
  "integer",
  "integer",
  "integer",
  "text",
  "text",
  "text",
  "text",
  "text",
  "text",
  "text",
  "text",
  "text",
  "text",
  "text",
  "text",
  "text",
  "text",
  "text",
  "text",
  "text",
  "integer",
  "integer",
  "decimal",
  "integer",
  "decimal",
  "decimal",
  "integer",
  "integer",
  "integer",
  "integer",
  "integer",
  "integer",
  "integer",
  "integer",
  "integer",
  "integer",
  "integer",
  "integer",
  "integer",
  "text",
  "integer",
  "integer",
  "integer",
  "integer",
  "integer",
  "integer",
  "integer",
  "text",
  "text",
  "text",
  "text",
  "integer",
  "integer",
  "integer",
  "integer",
  "integer",
  "integer",
  "decimal",
  "decimal",
  "integer",
  "decimal",
  "integer",
  "integer",
  "integer",
  "integer",
  "integer",
  "integer",
  "integer",
  "integer",
  "integer",
  "integer",
  "integer",
  "integer",
  "text",
  "integer",
  "text",
  "text",
  "text",
  "integer",
  "text",
  "text",
  "text",
  "integer",
  "text",
  "text",
  "text",
  "integer",
  "text",
  "text",
  "text",
  "integer",
  "text",
  "text",
  "text",
  "integer",
  "text",
  "text",
  "text",
  "integer",
  "text",
  "text",
  "text",
  "integer",
  "text",
  "text",
  "text",
  "integer",
  "text",
  "text",
  "text",
  "integer",
  "text",
  "text",
  "text",
  "integer",
  "text",
  "text",
  "text",
  "integer",
  "text",
  "text",
  "text",
  "integer",
  "text",
  "text",
  "text",
  "integer",
  "text",
  "text",
  "text",
  "integer",
  "text",
  "text",
  "text",
  "integer",
  "text",
  "text",
  "text",
  "integer",
  "text",
  "text",
  "text",
  "integer",
  "text",
  "text",
  "text",
  "integer",
  "text",
  "text",
  "text",
  "integer",
  "text",
  "text",
  "text",
  "text",
  "text",
  "text",
  "text",
  "text",
  "text",
  "text",
  "text",
  "Y/N",
  "text",
  "Y/N",
  "text",
  "text",
  "text",
  "text",
  "text",
  "text",
  "text",
  "text",
  "text",
  "text",
  "text",
  "text",
  "text",
  "text",
  "text",
  "text",
  "text",
  "text",
  "text",
  "text",
  "text",
  "text",
  "text",
  "text",
  "text",
  "text",
  "text",
  "text",
  "text",
  "text",
  "text",
  "text",
  "text",
  "text",
  "text",
  "text",
  "text",
  "text",
  "text",
  "text",
  "text",
  "text",
  "text",
  "text",
  "text",
  "text",
  "text",
  "text",
  "text",
  "text",
  "text",
  "text",
  "text",
  "text",
  "text",
  "text",
  "text",
  "text",
  "text",
  "text",
  "text",
  "text",
  "text",
  "text",
  "text",
  "text",
  "text",
  "text",
  "text",
  "text",
  "text",
  "text",
  "text",
  "text",
  "text",
  "text",
  "text",
  "text",
  "text",
  "text",
  "text",
  "text",
  "text",
  "text",
  "text",
  "text",
  "text",
  "text",
  "text",
  "text",
  "text",
  "text",
  "text",
  "text",
  "text",
  "text",
  "text",
  "text",
  "text",
  "text",
  "text",
  "text",
  "text",
  "text",
  "text",
  "text",
  "text"
];

const requiredHeadersName = [
  "Awd_CR1",
  "Awd_Amt1",
  "Awd_Status1",
  "Awd_CR2",
  "Awd_Amt2",
  "Awd_Status2",
  "Awd_CR3",
  "Awd_Amt3",
  "Awd_Status3",
  "Awd_CR4",
  "Awd_Amt4",
  "Awd_Status4",
  "Awd_CR5",
  "Awd_Amt5",
  "Awd_Status5",
  "Awd_CR6",
  "Awd_Amt6",
  "Awd_Status6",
  "Awd_CR7",
  "Awd_Amt7",
  "Awd_Status7",
  "Awd_CR8",
  "Awd_Amt8",
  "Awd_Status8",
  "Awd_CR9",
  "Awd_Amt9",
  "Awd_Status9",
  "Awd_CR10",
  "Awd_Amt10",
  "Awd_Status10",
  "Awd_CR11",
  "Awd_Amt11",
  "Awd_Status11",
  "Awd_CR12",
  "Awd_Amt12",
  "Awd_Status12",
  "Awd_CR13",
  "Awd_Amt13",
  "Awd_Status13",
  "Awd_CR14",
  "Awd_Amt14",
  "Awd_Status14",
  "Awd_CR15",
  "Awd_Amt15",
  "Awd_Status15",
  "Awd_CR16",
  "Awd_Amt16",
  "Awd_Status16",
  "Awd_CR17",
  "Awd_Amt17",
  "Awd_Status17",
  "Awd_CR18",
  "Awd_Amt18",
  "Awd_Status18",
  "Awd_CR19",
  "Awd_Amt19",
  "Awd_Status19",
  "Awd_CR20",
  "Awd_Amt20",
  "Awd_Status20",
  "Total_Performance_Gift", 
  "Total_Institutional_Merit_Gift", 
  "Total_Institutional_Need_Gift",
  "Total_Institutional_Other_Gift", 
  "Total_Institutional_Honors_Gift", 
  "Total_Institutional_Unfunded_Gift",
  "Total_Institutional_Gift", 
  "Total_Institutional_Work", 
  "Total_Federal_Work_Aid", 
  "Total_Loan_Aid",
  "Total_Employee_Benefit", 
  "Total_Tuition_Exchange", 
  "Total_Outside_Gift+Work+Loan",
  "Total_Merit+Need_Gift",
  "Institutional_Merit_As_%_Of_Need_Met",
  "Total_Ouside_Gift_Aid",
  "Total_Outside_Loan_Aid",
  "Total_Outside_Work_Aid",
  "Total_Private_Aid_G+W+L",
  "Total_Private_Gift_Aid",
  "Total_Private_Loan_Aid",
  "Total_Private_Work_Aid",
  "Total_Federal_Aid_G+W+L",
  "Total_Federal_Gift_Aid",
  "Total_Federal_Loan_Aid",
  "Total_State_Aid_G+W+L",
  "Total_State_Gift_Aid",
  "Total_Need_Based_Aid",
  "Total_Gift_Aid",
  "Total_Work_Aid",
  "Total_Elite_Gift"
];

const awardTypePatterns = {
  "Total_Performance_Gift": /^I[TA].G$/,
  "Total_Institutional_Merit_Gift": /^I[MI].G$/,
  "Total_Institutional_Need_Gift": /^IN.G$/,
  "Total_Institutional_Other_Gift": /^IO.G$/,
  "Total_Institutional_Honors_Gift": /^IH.G$/,
  "Total_Institutional_Unfunded_Gift": /^I.UG$/,
  "Total_Institutional_Gift": /^I..G$/,
  "Total_Institutional_Work": /^I..W$/,
  "Total_Federal_Work_Aid": /^F..W$/,
  "Total_Loan_Aid": /^...L$/,
  "Total_Employee_Benefit": /^E...$/,
  "Total_Tuition_Exchange": /^T...$/,
  "Total_Outside_Gift+Work+Loan": /^O...$/,
  "Total_Merit+Need_Gift": /^.[MN].G$/,
  "Institutional_Merit_As_%_Of_Need_Met": /^IM.G$/,
  "Total_Ouside_Gift_Aid": /^O..G$/,
  "Total_Outside_Loan_Aid": /^O..L$/,
  "Total_Outside_Work_Aid": /^O..W$/,
  "Total_Private_Aid_G+W+L": /^P...$/,
  "Total_Private_Gift_Aid": /^P..G$/,
  "Total_Private_Loan_Aid": /^P..L$/,
  "Total_Private_Work_Aid": /^P..W$/,
  "Total_Federal_Aid_G+W+L": /^F...$/,
  "Total_Federal_Gift_Aid": /^F..G$/,
  "Total_Federal_Loan_Aid": /^F..L$/,
  "Total_State_Aid_G+W+L": /^S...$/,
  "Total_State_Gift_Aid": /^S..G$/,
  "Total_Need_Based_Aid": /^.N..$/,
  "Total_Gift_Aid": /^...G$/,
  "Total_Work_Aid": /^...W$/,
  "Total_Elite_Gift": /^IP.G$/
};

const ynFlags = [
  "Y/N Student_In_County",
  "Y/N Bought_Through_Search",
  "Y/N Student_Inquired",
  "Y/N Stealth APP",
  "Y/N Student_Applied",
  "Y/N Student_Admitted",
  "Y/N Student_Readmitted",
  "Y/N Student_Confirmed",
  "Y/N Student_Cancelled",
  "Y/N Student_Enrolled",
  "Y/N International_Student",
  "Y/N Veteran",
  "Y/N Student_Religion=School_Denomination",
  "Y/N First_Generation_Student",
  "Y/N Emerging_Population",
  "Y/N Legacy_Student",
  "Y/N Early_Admit_Student",
  "Y/N Early_Enrollment_Decision",
  "Y/N Early_Aid",
  "Y/N Funded_Athlete",
  "Y/N Roster_Athlete",
  "Y/N Coach_Recruited_Athlete",
  "Y/N Recruited for Extracurricular1",
  "Y/N Recruited for Extracurricular2",
  "Y/N Is_Student_Test_Optional",
  "Y/N ACT_Official",
  "Y/N SAT_Official",
  "Y/N Student_Applied_To_Honors_Program",
  "Y/N Is_College_Data_Self-reported/Transcript",
  "Y/N Hispanic",
  "Y/N Did_Student_Submit_Our_FA_Application",
  "Y/N Will_Student_File_FAFSA",
  "Y/N FAFSA_Received",
  "Y/N Selected_For_Verification",
  "Y/N Is_ISIR_Valid",
  "Y/N Is_SAI_Estimated",
  "Y/N Is_Student_Seeking_Bachelor's_Degree",
  "Y/N Is_Student_Applying_As_Grad_Student",
  "Y/N Is_Student_Packaged",
  "Y/N Student_Accepted_Award",
  "Y/N Is_Student_Pell_Eligible",
  "Y/N Student/Parent_Denied_PLUS",
  "Y/N Is_Student_Receiving_Talent_Aid",
  "Y/N Student_Eligible_For_In-state_Tuition",
  "Y/N Zero_SAI_For_Student",
  "Y/N Student_Is_Employee_Benefit",
  "Y/N Student_Is_Tuition_Exchange",
  "Y/N Student_Is_PELL_Eligible",
  "Y/N Student_Is_State_Grant_Eligible",
  "Y/N Professional_Judgement_Performed",
  "Y/N Student_Persisted_To_Second_Term",
  "Y/N Student_Persisted_To_Second_Fall",
  "Y/N In Analysis",
];


const REQUIRED_HEADERS = [
  'First_Year/Transfer/Continuing/Readmit/Online',
  'Student_Admitted',
  'Student_Enrolled',
  'Admissions_Funnel_Stage',
  'Net_Tuition_Revenue',
  'Total_Discount_Rate',
  'NACUBO_Discount_Rate',
  'Net_Charges_To_Student',
  'Total_Institutional_Gift',
  'Total_Institutional_Unfunded_Gift'
];


module.exports = {
  desiredOrder,
  awardTypePatterns,
  requiredHeadersName,
  desiredOrderType,
  ynFlags,
  REQUIRED_HEADERS
};